version: '3.8'

services:
  nginx:
    build: nginx/
    container_name: image_converter_nginx
    ports:
      - ${PORT}:80
    restart: always
    depends_on:
      - backend

  backend:
    build: app/
    container_name: image_converter_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./app:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  postgres:
    image: postgres:16.2-alpine
    container_name: image_converter_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

volumes:
  postgres_data: